function q0_onclick()
{
document.getElementById('LINK_F').style.background='';
document.getElementById('LINK_F').style.color='';
document.getElementById('ADMIN_CONFIGURATION').style.visibility='hidden';
document.getElementById('ADMIN_CONFIGURATION').style.display='none';
document.getElementById('ABOUT_CMS').style.visibility='visible';
document.getElementById('ABOUT_CMS').style.display='';
document.getElementById('DATABASE').style.visibility='hidden';
document.getElementById('DATABASE').style.display='none';
document.getElementById('SITE_CONFIGURATION').style.visibility='hidden';
document.getElementById('SITE_CONFIGURATION').style.display='none';
document.getElementById('LINK_S').style.background='';
document.getElementById('LINK_S').style.color='';
document.getElementById('LINK_D').style.background='';
document.getElementById('LINK_D').style.color='';
document.getElementById('LINK_A').style.background='';
document.getElementById('LINK_A').style.color='';
document.getElementById('LINK_ABOUT').style.background='#1e282c';
document.getElementById('LINK_ABOUT').style.color='#fff';
document.getElementById('FILES').style.visibility='hidden';
document.getElementById('FILES').style.display='none';

}
function q3_onclick()
{
document.getElementById('LINK_F').style.background='';
document.getElementById('LINK_F').style.color='';
document.getElementById('ABOUT_CMS').style.visibility='hidden';
document.getElementById('ABOUT_CMS').style.display='none';
document.getElementById('ADMIN_CONFIGURATION').style.visibility='hidden';
document.getElementById('ADMIN_CONFIGURATION').style.display='none';
document.getElementById('DATABASE').style.visibility='visible';
document.getElementById('DATABASE').style.display='';
document.getElementById('SITE_CONFIGURATION').style.visibility='hidden';
document.getElementById('SITE_CONFIGURATION').style.display='none';
document.getElementById('LINK_S').style.background='';
document.getElementById('LINK_S').style.color='';
document.getElementById('LINK_D').style.background='#1e282c';
document.getElementById('LINK_D').style.color='#fff';
document.getElementById('LINK_A').style.background='';
document.getElementById('LINK_A').style.color='';
document.getElementById('LINK_ABOUT').style.background='';
document.getElementById('LINK_ABOUT').style.color='';
document.getElementById('FILES').style.visibility='hidden';
document.getElementById('FILES').style.display='none';

}
function q1_onclick()
{
document.getElementById('ABOUT_CMS').style.visibility='hidden';
document.getElementById('ABOUT_CMS').style.display='none';
document.getElementById('ABOUT_CMS').style.visibility='hidden';
document.getElementById('ABOUT_CMS').style.display='none';
document.getElementById('ADMIN_CONFIGURATION').style.visibility='hidden';
document.getElementById('ADMIN_CONFIGURATION').style.display='none';
document.getElementById('SITE_CONFIGURATION').style.visibility='visible';
document.getElementById('SITE_CONFIGURATION').style.display='';
document.getElementById('DATABASE').style.visibility='hidden';
document.getElementById('DATABASE').style.display='none';
document.getElementById('LINK_S').style.background='#1e282c';
document.getElementById('LINK_S').style.color='#fff';
document.getElementById('LINK_D').style.background='';
document.getElementById('LINK_D').style.color='';
document.getElementById('LINK_A').style.background='';
document.getElementById('LINK_A').style.color='';
document.getElementById('LINK_ABOUT').style.background='';
document.getElementById('LINK_ABOUT').style.color='';
document.getElementById('FILES').style.visibility='hidden';
document.getElementById('FILES').style.display='none';
document.getElementById('LINK_F').style.background='';
document.getElementById('LINK_F').style.color='';

}
function q4_onclick()
{
document.getElementById('FILES').style.visibility='visible';
document.getElementById('FILES').style.display='';
document.getElementById('ABOUT_CMS').style.visibility='hidden';
document.getElementById('ABOUT_CMS').style.display='none';
document.getElementById('ABOUT_CMS').style.visibility='hidden';
document.getElementById('ABOUT_CMS').style.display='none';
document.getElementById('ADMIN_CONFIGURATION').style.visibility='hidden';
document.getElementById('ADMIN_CONFIGURATION').style.display='none';
document.getElementById('SITE_CONFIGURATION').style.visibility='hidden';
document.getElementById('SITE_CONFIGURATION').style.display='none';
document.getElementById('DATABASE').style.visibility='hidden';
document.getElementById('DATABASE').style.display='none';
document.getElementById('LINK_S').style.background='';
document.getElementById('LINK_S').style.color='';
document.getElementById('LINK_D').style.background='';
document.getElementById('LINK_D').style.color='';
document.getElementById('LINK_A').style.background='';
document.getElementById('LINK_A').style.color='';
document.getElementById('LINK_ABOUT').style.background='';
document.getElementById('LINK_ABOUT').style.color='';
document.getElementById('LINK_F').style.background='#1e282c';
document.getElementById('LINK_F').style.color='#fff';

}
function q2_onclick()
{
document.getElementById('FILES').style.visibility='hidden';
document.getElementById('FILES').style.display='none';
document.getElementById('ABOUT_CMS').style.visibility='hidden';
document.getElementById('ABOUT_CMS').style.display='none';
document.getElementById('SITE_CONFIGURATION').style.visibility='hidden';
document.getElementById('SITE_CONFIGURATION').style.display='none';
document.getElementById('ADMIN_CONFIGURATION').style.visibility='visible';
document.getElementById('ADMIN_CONFIGURATION').style.display='';
document.getElementById('DATABASE').style.visibility='hidden';
document.getElementById('DATABASE').style.display='none';
document.getElementById('LINK_S').style.background='';
document.getElementById('LINK_S').style.color='';
document.getElementById('LINK_D').style.background='';
document.getElementById('LINK_D').style.color='';
document.getElementById('LINK_A').style.background='#1e282c';
document.getElementById('LINK_A').style.color='#fff';
document.getElementById('LINK_F').style.background='';
document.getElementById('LINK_F').style.color='';
document.getElementById('LINK_ABOUT').style.background='';
document.getElementById('LINK_ABOUT').style.color='';

}
function hideNext(){
	document.getElementById('next').style.visibility='hidden';
	document.getElementById('next').style.display='none';
}